from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime
import httpx
import os

app = FastAPI(
    title="ERP Analytics Service",
    description="Python FastAPI microservice for reports & analytics",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

NODE_API = os.getenv("NODE_API_URL")

class ReportRequest(BaseModel):
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    report_type: str = "sales"

class SalesPrediction(BaseModel):
    product_id: str
    historical_sales: List[float]

@app.get("/")
def root():
    return {
        "service": "ERP Python Analytics Service",
        "status": "running",
        "version": "1.0.0",
        "endpoints": ["/health", "/reports/sales", "/reports/inventory", "/predict/sales"]
    }

@app.get("/health")
def health():
    return {"status": "healthy", "timestamp": datetime.utcnow().isoformat()}

@app.get("/reports/sales-summary")
async def sales_summary():
    """Fetch sales data from Node API and generate summary"""
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            # This is a mock since we don't have auth token here easily
            # In production, pass token or use internal network
            return {
                "success": True,
                "message": "Sales summary generated by Python service",
                "data": {
                    "total_revenue": 1250000,
                    "total_orders": 48,
                    "average_order_value": 26041.67,
                    "top_products": [
                        {"name": "Laptop Dell XPS 15", "units": 12, "revenue": 3000000},
                        {"name": "Standing Desk", "units": 8, "revenue": 360000},
                        {"name": "Office Chair", "units": 15, "revenue": 270000}
                    ],
                    "generated_at": datetime.utcnow().isoformat(),
                    "engine": "Python FastAPI + Pandas"
                }
            }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/reports/inventory-analysis")
async def inventory_analysis():
    return {
        "success": True,
        "data": {
            "total_sku": 5,
            "low_stock_items": 1,
            "inventory_health_score": 82,
            "recommendations": [
                "Reorder Wireless Mouse Logitech (stock below minimum)",
                "Consider increasing stock of high-demand laptops",
                "Stationery items are well stocked"
            ],
            "abc_analysis": {
                "A_items": ["Laptop Dell XPS 15", "Standing Desk"],
                "B_items": ["Office Chair Ergonomic"],
                "C_items": ["A4 Paper Ream", "Wireless Mouse"]
            },
            "generated_at": datetime.utcnow().isoformat()
        }
    }

@app.post("/predict/sales")
async def predict_sales(data: SalesPrediction):
    """Simple moving average prediction"""
    if len(data.historical_sales) < 3:
        raise HTTPException(status_code=400, detail="Need at least 3 data points")

    avg = sum(data.historical_sales[-3:]) / 3
    trend = (data.historical_sales[-1] - data.historical_sales[-3]) / 2
    prediction = max(0, round(avg + trend, 2))

    return {
        "success": True,
        "product_id": data.product_id,
        "historical": data.historical_sales,
        "predicted_next_period": prediction,
        "method": "3-period moving average + trend",
        "confidence": "medium"
    }

@app.get("/analytics/employee-distribution")
async def employee_distribution():
    return {
        "success": True,
        "data": {
            "departments": [
                {"name": "IT", "count": 1, "percentage": 25},
                {"name": "HR", "count": 1, "percentage": 25},
                {"name": "Sales", "count": 1, "percentage": 25},
                {"name": "Finance", "count": 1, "percentage": 25}
            ],
            "total": 4
        }
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
